notifications:
  email: false
  slack:
    rooms:
      secure: MIS2NjYwk/52N/KirJT/4mUKabVNJxRFj5KcFkDV3G1R+Q+RZ/9PnOYgIROIKq62kfEP2MldkiIXXAK6zEx1NfGFEM62/ee42C2xXrmYG1+RtXBg7WGccgbxOxlY70twDYmoHEYsU17uDZSJwAYtzF7MtHQHNc+5c78mVl02xaC+AJWlKr4fsZ3IuFYqgrt6osAZZWsN13ISt5R8dOwvS7MiHTtR7cyxAifvVr6urt8tvkHS8v3ubB570Z24sDQc11IaQQQmotkT9n1LtBl4Xqas1xaUcp1qigq6/lN3D+bJ0MXogtyj11Dfa2IzYF4CnbztVMojFOfAbeYTV8HjavPCTFKL0Qb3UaSLShclVwLcdNhOVw/yvYP7651FX/A/egBY7VJFLsTtTwLHXTzhrUA7SJureSF+ZCvfG4IMMTIo7y8ZgFCvg9xBi7hb+ILt8nAWE52ZDXSSxEJX2JhhWk9acEKC3eH1Fsaj8/uTIy/yUt2zWAPOZv51C6UxzqTnX6FZ5bj2z/cfA8y1JPurHWQpfJqhlydhfDYdM1cQYaKBosHkW5KimNGFRsj9TJ+6UFJnnmLUhlUaCbpS9xyDHTP/Num2glcMqdlLPzA//iMhONLfbKnQ9Xfgs0wSCPaSZsIU67en044vUO9Ik7On0LtFQlGxjdQGVfvITLCGxcs=
    on_success: always
    on_failure: always

stages:
- name: TEST
  if: commit_message !~ /(skip[ _-]test)/    
- name: DOC
  if: commit_message =~ /\[build doc\]/
- name: EXTRAS
  if: commit_message !~ /(skip[ _-]extras)/

jobs:
  include:

  - stage: TEST
    language: node_js
    node_js:
    - '16'  
    services:
    - docker
    - mongodb
    env:
    - CC_TEST_REPORTER_ID=42cc93bb51067210ce09b5b3b98a6d5cc4d9c432f51d5844d4e61c36fff160fc
    install:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - bash .travis.test.sh
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

  - stage: DOC
    language: node_js
    node_js:
    - '16'
    install: true
    script: bash .travis.doc.sh
    deploy:
      provider: pages
      local-dir: docs/.vuepress/dist
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
