graph LR
	before{none before all}
    
    after{none after all}

    before --> hook1(populateSubjects)
    hook1 --> hook2(populateResource)
    hook2 -->|before| CREATE[CREATE]
    CREATE -->|after| after
    
    before --> hook3(populateSubjects)
    hook3 --> hook4(populateResource)
    hook4 -->|before| REMOVE[REMOVE]
    REMOVE -->|after| after
    
    linkStyle default stroke-width:2px,fill:none,stroke:black
    classDef hookClass fill:#f96,stroke:#333,stroke-width:2px
    class hook1,hook2,hook3,hook4 hookClass
    classDef operationClass fill:#9c6,stroke:#333,stroke-width:2px
    class FIND,GET,CREATE,UPDATE,PATCH,REMOVE operationClass