graph LR
    beforeAll{before all}
    bahook(ba-hook) --> beforeAll

    afterAll{after all}
    afterAll --> aahook(aa-hook)

    beforeAll --> bfhook(bf-hook)
    bfhook -->|before| FIND[FIND]
    FIND -->|after| afhook(af-hook)
    afhook --> afterAll
    
    beforeAll --> bghook(bg-hook)
    bghook -->|before| GET[GET]
    GET -->|after| aghook(ag-hook)
    aghook --> afterAll

    beforeAll --> bchook(bc-hook)
    bchook -->|before| CREATE[CREATE]
    CREATE -->|after| achook(ac-hook)
    achook --> afterAll

    beforeAll --> buhook(bu-hook)
    buhook -->|before| UPDATE[UPDATE]
    UPDATE -->|after| auhook(au-hook)
    auhook --> afterAll

    beforeAll --> bphook(bp-hook)
    bphook -->|before| PATCH[PATCH]
    PATCH -->|after| aphook(ap-hook)
    aphook --> afterAll

    beforeAll --> brhook(br-hook)
    brhook -->|before| REMOVE[REMOVE]
    REMOVE -->|after| arhook(ar-hook)
    arhook --> afterAll

    linkStyle default stroke-width:2px,fill:none,stroke:black
    classDef hookClass fill:#f96,stroke:#333,stroke-width:2px
    class bahook,aahook,bfhook,afhook,bghook,aghook,bchook,achook,buhook,auhook,bphook,aphook,brhook,arhook hookClass
    classDef operationClass fill:#9c6,stroke:#333,stroke-width:2px
    class FIND,GET,CREATE,UPDATE,PATCH,REMOVE operationClass