graph TB
	before{none before all}

    after{none after all}

    before --> FIND[FIND]
    FIND --> after

    before --> hook1("disallow('external')")
    hook1 --> GET[GET]
    GET --> after

    before --> hook2(populateTagResource)
    hook2 --> hook3(addTagIfNew)
    hook3 --> CREATE[CREATE]
    CREATE --> hook4(tagResource)
    hook4 --> after
    
    before --> hook5(disallow)
    hook5 --> UPDATE[UPDATE]
    UPDATE --> after
    
    before --> hook6("disallow('external')")
    hook6 --> PATCH[PATCH]
    PATCH --> after

    before --> hook7(populateTagResource)
    hook7 --> hook8(removeTagIfUnused)
    hook8 --> REMOVE[REMOVE]
    REMOVE --> hook9(untagResource)
    hook9 --> after
    
    linkStyle default stroke-width:2px,fill:none,stroke:black
    classDef hookClass fill:#f96,stroke:#333,stroke-width:2px
    class hook1,hook2,hook3,hook4,hook5,hook6,hook7,hook8,hook9 hookClass
    classDef operationClass fill:#9c6,stroke:#333,stroke-width:2px
    class FIND,GET,CREATE,UPDATE,PATCH,REMOVE operationClass