graph TB
    beforeAll{before all}
    
    afterAll{after all}
    afterAll --> hook1(unprocessTime)
    hook1 --> hook2(convertToJson)
    
    beforeAll --> hook3(marshallSpatialQuery)
    hook3 --> FIND[FIND]
    FIND --> afterAll

    beforeAll --> GET[GET]
    GET --> afterAll

    beforeAll --> hook4(processTime)
    hook4 --> hook5(convertToString)
    hook5 --> CREATE[CREATE]
    CREATE --> hook6(registerAlert)
    hook6 --> afterAll

    beforeAll --> hook7(disallow)
    hook7 --> UPDATE[UPDATE]
    UPDATE --> afterAll

    beforeAll --> hook8(processTime)
    hook8 --> hook9(convertToString)
    hook9 --> PATCH[PATCH]
    PATCH --> afterAll

    beforeAll --> hook10(unregisterAlert)
    hook10 --> REMOVE[REMOVE]
    REMOVE --> afterAll

    linkStyle default stroke-width:2px,fill:none,stroke:black
    classDef hookClass fill:#f96,stroke:#333,stroke-width:2px
    class hook1,hook2,hook3,hook4,hook5,hook6,hook7,hook8,hook9,hook10,hook11,hook12,hook13 hookClass
    classDef operationClass fill:#9c6,stroke:#333,stroke-width:2px
    class FIND,GET,CREATE,UPDATE,PATCH,REMOVE operationClass