graph TB
    beforeAll{marshallTimeQuery}
    
    afterAll{after all}
    afterAll --> hook1(unprocessTime)
    
    beforeAll --> hook2(marshallComparisonQuery)
    hook2 --> hook3(marshallSortQuery)
    hook3 --> hook4(marshallSpatialQuery)
    hook4 --> hook5(aggregateFeaturesQuery)
    hook5 --> FIND[FIND]
    FIND --> hook6(asGeoJson)
    hook6 --> afterAll

    beforeAll --> GET[GET]
    GET --> afterAll

    beforeAll --> hook7(processTime)
    hook7 --> CREATE[CREATE]
    CREATE --> afterAll

    beforeAll --> hook8(processTime)
    hook8 --> UPDATE[UPDATE]
    UPDATE --> afterAll

    beforeAll --> hook9(processTime)
    hook9 --> PATCH[PATCH]
    PATCH --> afterAll

    beforeAll --> hook10(marshallComparisonQuery)
    hook10 --> hook11(marshallSpatialQuery)
    hook11 --> REMOVE[REMOVE]
    REMOVE --> afterAll

    linkStyle default stroke-width:2px,fill:none,stroke:black
    classDef hookClass fill:#f96,stroke:#333,stroke-width:2px
    class hook1,hook2,hook3,hook4,hook5,hook6,hook7,hook8,hook9,hook10,hook11,hook12,hook13 hookClass
    classDef operationClass fill:#9c6,stroke:#333,stroke-width:2px
    class FIND,GET,CREATE,UPDATE,PATCH,REMOVE operationClass