name: KDK's CI
on:
  push:
    branches:
      - gha
jobs:
  ci:
    strategy:
      fail-fast: false
      # matrix:
      #   node: [ 16, 18 ]
      #   mongo: [ 4, 5 ]
    # name: Tests / Node ${{ matrix.node }} / Mongo ${{ matrix.mongo }}
    runs-on: ubuntu-22.04
    # container:
    #   image: harbor.portal.kalisio.com/kalisio/ci-kdk:latest
    #   # Run using Github Actions specific user in our container
    #   options: --user 1001
    # steps:
    #   - name: Checkout repo
    #     uses: actions/checkout@v4
    #   - name: Run tests
    #     env:
    #       SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    #       GITHUB_DEVELOPMENT_PAT: ${{ secrets.GH_DEVELOPMENT_PAT }}
    #     run: bash ./scripts/test.sh
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Cache requirements
        uses: actions/cache@v3
        with:
          key: requirements
          path: ${{ runner.temp }}/dl
      - name: Normalize env
        run: bash ./scripts/normalize-gha.sh
      - name: Run tests
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
          GITHUB_DEVELOPMENT_PAT: ${{ secrets.GH_DEVELOPMENT_PAT }}
        # run: bash ./scripts/test.sh -n ${{ matrix.node }} -m ${{ matrix.mongo }}
        run: bash ./scripts/test.sh
